[build]
  publish = "."
  functions = "netlify/functions"

[dev]
  functions = "netlify/functions"

[[headers]]
  for = "/*"
  [headers.values]
   Content-Security-Policy = "default-src 'self'; script-src 'self' 'sha256-oShY008UHXAwjW6kyqFDVDGn08bDVBUSaZ0rQyavqVo=' 'sha256-yB30O3yrwQ8qS6jj/+j4DS5y5agKrf7prApcMQLxiKM=' 'sha256-dPu44xhlxc+TsgRRN5Q80s3nuxU3XpX6AdmIEUHSrLw=' 'sha256-dxu25Pk+UucDQCobwcWmD1/pZK2zBzhh73RBWy3Wkpw=' 'sha256-1mWQH20+d48Aj1YGmybkD0sAtth7cPBhqI+22AeIbVk=' 'sha256-1yjGID0Z05GsRZeU1/k+BtK5IFKIsrnGFG4ll4WTG5o=' 'sha256-pYnSxznCKwM3vVIMi0zb637zBVUztA+AqZWz8qgNS/8=' 'sha256-WqlSX0FHbwNVKjQVs9N00gA0GSwcuUV2Dk8bznuOfQk=' 'sha256-DE3ef0W/h9omzNEUHag1IKVvHtQS6HRgvttQC22+k3Q=' 'sha256-9sdFwxGWLAF9R0KAynuBeeqm2AEQDvwzdgFrolLdl4o=' 'sha256-wxWzc4T0BCz9NTBrmrhtLIil3l35WkixAFcDqVVuLUo=' 'sha256-zXDgOrxxapBAidCfvkYhlC2bWVpX5xNYG+3pZjA/K38=' 'sha256-ieCdeu/aeuw7cUWW+cXNr85VJDldKKdSR96kbODTgrY=' 'sha256-y9bUG6hAP+8Hn089o/hZQis6RvJTB/hfgXoiNzTAjWw=' 'sha256-Z4sAI8RXio17FFYjK+pcz4vM6hAHnBm32t7tLKHH8lY=' https://www.googletagmanager.com https://www.google-analytics.com; style-src 'self' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; connect-src 'self' https://www.google-analytics.com https://www.googletagmanager.com https://script.google.com; img-src 'self' https: data:; frame-src 'self' https://drive.google.com; frame-ancestors 'none'; base-uri 'self'"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

[[redirects]]
  from = "/flat-society.html"
  to = "/"
  status = 301
